/* Conquer Space
 * Copyright (C) 2021-2023 Conquer Space
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
#include "engine/userinput.h"

#include <GLFW/glfw3.h>
#include <RmlUi/Core/Input.h>

int cqsp::engine::GetRmlUiKey(int glfw_key) {
    switch (glfw_key) {
        case GLFW_KEY_A:
            return Rml::Input::KI_A;
        case GLFW_KEY_B:
            return Rml::Input::KI_B;
        case GLFW_KEY_C:
            return Rml::Input::KI_C;
        case GLFW_KEY_D:
            return Rml::Input::KI_D;
        case GLFW_KEY_E:
            return Rml::Input::KI_E;
        case GLFW_KEY_F:
            return Rml::Input::KI_F;
        case GLFW_KEY_G:
            return Rml::Input::KI_G;
        case GLFW_KEY_H:
            return Rml::Input::KI_H;
        case GLFW_KEY_I:
            return Rml::Input::KI_I;
        case GLFW_KEY_J:
            return Rml::Input::KI_J;
        case GLFW_KEY_K:
            return Rml::Input::KI_K;
        case GLFW_KEY_L:
            return Rml::Input::KI_L;
        case GLFW_KEY_M:
            return Rml::Input::KI_M;
        case GLFW_KEY_N:
            return Rml::Input::KI_N;
        case GLFW_KEY_O:
            return Rml::Input::KI_O;
        case GLFW_KEY_P:
            return Rml::Input::KI_P;
        case GLFW_KEY_Q:
            return Rml::Input::KI_Q;
        case GLFW_KEY_R:
            return Rml::Input::KI_R;
        case GLFW_KEY_S:
            return Rml::Input::KI_S;
        case GLFW_KEY_T:
            return Rml::Input::KI_T;
        case GLFW_KEY_U:
            return Rml::Input::KI_U;
        case GLFW_KEY_V:
            return Rml::Input::KI_V;
        case GLFW_KEY_W:
            return Rml::Input::KI_W;
        case GLFW_KEY_X:
            return Rml::Input::KI_X;
        case GLFW_KEY_Y:
            return Rml::Input::KI_Y;
        case GLFW_KEY_Z:
            return Rml::Input::KI_Z;
        case GLFW_KEY_0:
            return Rml::Input::KI_0;
        case GLFW_KEY_1:
            return Rml::Input::KI_1;
        case GLFW_KEY_2:
            return Rml::Input::KI_2;
        case GLFW_KEY_3:
            return Rml::Input::KI_3;
        case GLFW_KEY_4:
            return Rml::Input::KI_4;
        case GLFW_KEY_5:
            return Rml::Input::KI_5;
        case GLFW_KEY_6:
            return Rml::Input::KI_6;
        case GLFW_KEY_7:
            return Rml::Input::KI_7;
        case GLFW_KEY_8:
            return Rml::Input::KI_8;
        case GLFW_KEY_9:
            return Rml::Input::KI_9;
        case GLFW_KEY_KP_0:
            return Rml::Input::KI_NUMPAD0;
        case GLFW_KEY_KP_1:
            return Rml::Input::KI_NUMPAD1;
        case GLFW_KEY_KP_2:
            return Rml::Input::KI_NUMPAD2;
        case GLFW_KEY_KP_3:
            return Rml::Input::KI_NUMPAD3;
        case GLFW_KEY_KP_4:
            return Rml::Input::KI_NUMPAD4;
        case GLFW_KEY_KP_5:
            return Rml::Input::KI_NUMPAD5;
        case GLFW_KEY_KP_6:
            return Rml::Input::KI_NUMPAD6;
        case GLFW_KEY_KP_7:
            return Rml::Input::KI_NUMPAD7;
        case GLFW_KEY_KP_8:
            return Rml::Input::KI_NUMPAD8;
        case GLFW_KEY_KP_9:
            return Rml::Input::KI_NUMPAD9;
        case GLFW_KEY_LEFT:
            return Rml::Input::KI_LEFT;
        case GLFW_KEY_RIGHT:
            return Rml::Input::KI_RIGHT;
        case GLFW_KEY_UP:
            return Rml::Input::KI_UP;
        case GLFW_KEY_DOWN:
            return Rml::Input::KI_DOWN;
        case GLFW_KEY_KP_ADD:
            return Rml::Input::KI_ADD;
        case GLFW_KEY_BACKSPACE:
            return Rml::Input::KI_BACK;
        case GLFW_KEY_DELETE:
            return Rml::Input::KI_DELETE;
        case GLFW_KEY_KP_DIVIDE:
            return Rml::Input::KI_DIVIDE;
        case GLFW_KEY_END:
            return Rml::Input::KI_END;
        case GLFW_KEY_ESCAPE:
            return Rml::Input::KI_ESCAPE;
        case GLFW_KEY_F1:
            return Rml::Input::KI_F1;
        case GLFW_KEY_F2:
            return Rml::Input::KI_F2;
        case GLFW_KEY_F3:
            return Rml::Input::KI_F3;
        case GLFW_KEY_F4:
            return Rml::Input::KI_F4;
        case GLFW_KEY_F5:
            return Rml::Input::KI_F5;
        case GLFW_KEY_F6:
            return Rml::Input::KI_F6;
        case GLFW_KEY_F7:
            return Rml::Input::KI_F7;
        case GLFW_KEY_F8:
            return Rml::Input::KI_F8;
        case GLFW_KEY_F9:
            return Rml::Input::KI_F9;
        case GLFW_KEY_F10:
            return Rml::Input::KI_F10;
        case GLFW_KEY_F11:
            return Rml::Input::KI_F11;
        case GLFW_KEY_F12:
            return Rml::Input::KI_F12;
        case GLFW_KEY_F13:
            return Rml::Input::KI_F13;
        case GLFW_KEY_F14:
            return Rml::Input::KI_F14;
        case GLFW_KEY_F15:
            return Rml::Input::KI_F15;
        case GLFW_KEY_HOME:
            return Rml::Input::KI_HOME;
        case GLFW_KEY_INSERT:
            return Rml::Input::KI_INSERT;
        case GLFW_KEY_LEFT_CONTROL:
            return Rml::Input::KI_LCONTROL;
        case GLFW_KEY_LEFT_SHIFT:
            return Rml::Input::KI_LSHIFT;
        case GLFW_KEY_KP_MULTIPLY:
            return Rml::Input::KI_MULTIPLY;
        case GLFW_KEY_PAUSE:
            return Rml::Input::KI_PAUSE;
        case GLFW_KEY_RIGHT_CONTROL:
            return Rml::Input::KI_RCONTROL;
        case GLFW_KEY_KP_ENTER:
            return Rml::Input::KI_RETURN;
        case GLFW_KEY_RIGHT_SHIFT:
            return Rml::Input::KI_RSHIFT;
        case GLFW_KEY_SPACE:
            return Rml::Input::KI_SPACE;
        case GLFW_KEY_KP_SUBTRACT:
            return Rml::Input::KI_SUBTRACT;
        case GLFW_KEY_TAB:
            return Rml::Input::KI_TAB;
        default:
            return Rml::Input::KI_UNKNOWN;
    }
}

int cqsp::engine::GetAsciiKey(int glfw_key) { return 0; }

cqsp::engine::KeyInput cqsp::engine::GetKey(int key) {
    switch (key) {
        case GLFW_KEY_SPACE:
            return KeyInput::KEY_SPACE;
        case GLFW_KEY_APOSTROPHE:
            return KeyInput::KEY_APOSTROPHE;
        case GLFW_KEY_COMMA:
            return KeyInput::KEY_COMMA;
        case GLFW_KEY_MINUS:
            return KeyInput::KEY_MINUS;
        case GLFW_KEY_PERIOD:
            return KeyInput::KEY_PERIOD;
        case GLFW_KEY_SLASH:
            return KeyInput::KEY_SLASH;
        case GLFW_KEY_0:
            return KeyInput::KEY_0;
        case GLFW_KEY_1:
            return KeyInput::KEY_1;
        case GLFW_KEY_2:
            return KeyInput::KEY_2;
        case GLFW_KEY_3:
            return KeyInput::KEY_3;
        case GLFW_KEY_4:
            return KeyInput::KEY_4;
        case GLFW_KEY_5:
            return KeyInput::KEY_5;
        case GLFW_KEY_6:
            return KeyInput::KEY_6;
        case GLFW_KEY_7:
            return KeyInput::KEY_7;
        case GLFW_KEY_8:
            return KeyInput::KEY_8;
        case GLFW_KEY_9:
            return KeyInput::KEY_9;
        case GLFW_KEY_SEMICOLON:
            return KeyInput::KEY_SEMICOLON;
        case GLFW_KEY_EQUAL:
            return KeyInput::KEY_EQUAL;
        case GLFW_KEY_A:
            return KeyInput::KEY_A;
        case GLFW_KEY_B:
            return KeyInput::KEY_B;
        case GLFW_KEY_C:
            return KeyInput::KEY_C;
        case GLFW_KEY_D:
            return KeyInput::KEY_D;
        case GLFW_KEY_E:
            return KeyInput::KEY_E;
        case GLFW_KEY_F:
            return KeyInput::KEY_F;
        case GLFW_KEY_G:
            return KeyInput::KEY_G;
        case GLFW_KEY_H:
            return KeyInput::KEY_H;
        case GLFW_KEY_I:
            return KeyInput::KEY_I;
        case GLFW_KEY_J:
            return KeyInput::KEY_J;
        case GLFW_KEY_K:
            return KeyInput::KEY_K;
        case GLFW_KEY_L:
            return KeyInput::KEY_L;
        case GLFW_KEY_M:
            return KeyInput::KEY_M;
        case GLFW_KEY_N:
            return KeyInput::KEY_N;
        case GLFW_KEY_O:
            return KeyInput::KEY_O;
        case GLFW_KEY_P:
            return KeyInput::KEY_P;
        case GLFW_KEY_Q:
            return KeyInput::KEY_Q;
        case GLFW_KEY_R:
            return KeyInput::KEY_R;
        case GLFW_KEY_S:
            return KeyInput::KEY_S;
        case GLFW_KEY_T:
            return KeyInput::KEY_T;
        case GLFW_KEY_U:
            return KeyInput::KEY_U;
        case GLFW_KEY_V:
            return KeyInput::KEY_V;
        case GLFW_KEY_W:
            return KeyInput::KEY_W;
        case GLFW_KEY_X:
            return KeyInput::KEY_X;
        case GLFW_KEY_Y:
            return KeyInput::KEY_Y;
        case GLFW_KEY_Z:
            return KeyInput::KEY_Z;
        case GLFW_KEY_LEFT_BRACKET:
            return KeyInput::KEY_LEFT_BRACKET;
        case GLFW_KEY_BACKSLASH:
            return KeyInput::KEY_BACKSLASH;
        case GLFW_KEY_RIGHT_BRACKET:
            return KeyInput::KEY_RIGHT_BRACKET;
        case GLFW_KEY_GRAVE_ACCENT:
            return KeyInput::KEY_GRAVE_ACCENT;
        case GLFW_KEY_WORLD_1:
            return KeyInput::KEY_WORLD_1;
        case GLFW_KEY_WORLD_2:
            return KeyInput::KEY_WORLD_2;
        case GLFW_KEY_ESCAPE:
            return KeyInput::KEY_ESCAPE;
        case GLFW_KEY_ENTER:
            return KeyInput::KEY_ENTER;
        case GLFW_KEY_TAB:
            return KeyInput::KEY_TAB;
        case GLFW_KEY_BACKSPACE:
            return KeyInput::KEY_BACKSPACE;
        case GLFW_KEY_INSERT:
            return KeyInput::KEY_INSERT;
        case GLFW_KEY_DELETE:
            return KeyInput::KEY_DELETE;
        case GLFW_KEY_RIGHT:
            return KeyInput::KEY_RIGHT;
        case GLFW_KEY_LEFT:
            return KeyInput::KEY_LEFT;
        case GLFW_KEY_DOWN:
            return KeyInput::KEY_DOWN;
        case GLFW_KEY_UP:
            return KeyInput::KEY_UP;
        case GLFW_KEY_PAGE_UP:
            return KeyInput::KEY_PAGE_UP;
        case GLFW_KEY_PAGE_DOWN:
            return KeyInput::KEY_PAGE_DOWN;
        case GLFW_KEY_HOME:
            return KeyInput::KEY_HOME;
        case GLFW_KEY_END:
            return KeyInput::KEY_END;
        case GLFW_KEY_CAPS_LOCK:
            return KeyInput::KEY_CAPS_LOCK;
        case GLFW_KEY_SCROLL_LOCK:
            return KeyInput::KEY_SCROLL_LOCK;
        case GLFW_KEY_NUM_LOCK:
            return KeyInput::KEY_NUM_LOCK;
        case GLFW_KEY_PRINT_SCREEN:
            return KeyInput::KEY_PRINT_SCREEN;
        case GLFW_KEY_PAUSE:
            return KeyInput::KEY_PAUSE;
        case GLFW_KEY_F1:
            return KeyInput::KEY_F1;
        case GLFW_KEY_F2:
            return KeyInput::KEY_F2;
        case GLFW_KEY_F3:
            return KeyInput::KEY_F3;
        case GLFW_KEY_F4:
            return KeyInput::KEY_F4;
        case GLFW_KEY_F5:
            return KeyInput::KEY_F5;
        case GLFW_KEY_F6:
            return KeyInput::KEY_F6;
        case GLFW_KEY_F7:
            return KeyInput::KEY_F7;
        case GLFW_KEY_F8:
            return KeyInput::KEY_F8;
        case GLFW_KEY_F9:
            return KeyInput::KEY_F9;
        case GLFW_KEY_F10:
            return KeyInput::KEY_F10;
        case GLFW_KEY_F11:
            return KeyInput::KEY_F11;
        case GLFW_KEY_F12:
            return KeyInput::KEY_F12;
        case GLFW_KEY_F13:
            return KeyInput::KEY_F13;
        case GLFW_KEY_F14:
            return KeyInput::KEY_F14;
        case GLFW_KEY_F15:
            return KeyInput::KEY_F15;
        case GLFW_KEY_F16:
            return KeyInput::KEY_F16;
        case GLFW_KEY_F17:
            return KeyInput::KEY_F17;
        case GLFW_KEY_F18:
            return KeyInput::KEY_F18;
        case GLFW_KEY_F19:
            return KeyInput::KEY_F19;
        case GLFW_KEY_F20:
            return KeyInput::KEY_F20;
        case GLFW_KEY_F21:
            return KeyInput::KEY_F21;
        case GLFW_KEY_F22:
            return KeyInput::KEY_F22;
        case GLFW_KEY_F23:
            return KeyInput::KEY_F23;
        case GLFW_KEY_F24:
            return KeyInput::KEY_F24;
        case GLFW_KEY_F25:
            return KeyInput::KEY_F25;
        case GLFW_KEY_KP_0:
            return KeyInput::KEY_KP_0;
        case GLFW_KEY_KP_1:
            return KeyInput::KEY_KP_1;
        case GLFW_KEY_KP_2:
            return KeyInput::KEY_KP_2;
        case GLFW_KEY_KP_3:
            return KeyInput::KEY_KP_3;
        case GLFW_KEY_KP_4:
            return KeyInput::KEY_KP_4;
        case GLFW_KEY_KP_5:
            return KeyInput::KEY_KP_5;
        case GLFW_KEY_KP_6:
            return KeyInput::KEY_KP_6;
        case GLFW_KEY_KP_7:
            return KeyInput::KEY_KP_7;
        case GLFW_KEY_KP_8:
            return KeyInput::KEY_KP_8;
        case GLFW_KEY_KP_9:
            return KeyInput::KEY_KP_9;
        case GLFW_KEY_KP_DECIMAL:
            return KeyInput::KEY_KP_DECIMAL;
        case GLFW_KEY_KP_DIVIDE:
            return KeyInput::KEY_KP_DIVIDE;
        case GLFW_KEY_KP_MULTIPLY:
            return KeyInput::KEY_KP_MULTIPLY;
        case GLFW_KEY_KP_SUBTRACT:
            return KeyInput::KEY_KP_SUBTRACT;
        case GLFW_KEY_KP_ADD:
            return KeyInput::KEY_KP_ADD;
        case GLFW_KEY_KP_ENTER:
            return KeyInput::KEY_KP_ENTER;
        case GLFW_KEY_KP_EQUAL:
            return KeyInput::KEY_KP_EQUAL;
        case GLFW_KEY_LEFT_SHIFT:
            return KeyInput::KEY_LEFT_SHIFT;
        case GLFW_KEY_LEFT_CONTROL:
            return KeyInput::KEY_LEFT_CONTROL;
        case GLFW_KEY_LEFT_ALT:
            return KeyInput::KEY_LEFT_ALT;
        case GLFW_KEY_LEFT_SUPER:
            return KeyInput::KEY_LEFT_SUPER;
        case GLFW_KEY_RIGHT_SHIFT:
            return KeyInput::KEY_RIGHT_SHIFT;
        case GLFW_KEY_RIGHT_CONTROL:
            return KeyInput::KEY_RIGHT_CONTROL;
        case GLFW_KEY_RIGHT_ALT:
            return KeyInput::KEY_RIGHT_ALT;
        case GLFW_KEY_RIGHT_SUPER:
            return KeyInput::KEY_RIGHT_SUPER;
        case GLFW_KEY_MENU:
            return KeyInput::KEY_MENU;
        default:
            return KeyInput::KEY_F25;
    }
}

int cqsp::engine::GetGlfwKey(KeyInput key) {
    switch (key) {
        case KeyInput::KEY_SPACE:
            return GLFW_KEY_SPACE;
        case KeyInput::KEY_APOSTROPHE:
            return GLFW_KEY_APOSTROPHE;
        case KeyInput::KEY_COMMA:
            return GLFW_KEY_COMMA;
        case KeyInput::KEY_MINUS:
            return GLFW_KEY_MINUS;
        case KeyInput::KEY_PERIOD:
            return GLFW_KEY_PERIOD;
        case KeyInput::KEY_SLASH:
            return GLFW_KEY_SLASH;
        case KeyInput::KEY_0:
            return GLFW_KEY_0;
        case KeyInput::KEY_1:
            return GLFW_KEY_1;
        case KeyInput::KEY_2:
            return GLFW_KEY_2;
        case KeyInput::KEY_3:
            return GLFW_KEY_3;
        case KeyInput::KEY_4:
            return GLFW_KEY_4;
        case KeyInput::KEY_5:
            return GLFW_KEY_5;
        case KeyInput::KEY_6:
            return GLFW_KEY_6;
        case KeyInput::KEY_7:
            return GLFW_KEY_7;
        case KeyInput::KEY_8:
            return GLFW_KEY_8;
        case KeyInput::KEY_9:
            return GLFW_KEY_9;
        case KeyInput::KEY_SEMICOLON:
            return GLFW_KEY_SEMICOLON;
        case KeyInput::KEY_EQUAL:
            return GLFW_KEY_EQUAL;
        case KeyInput::KEY_A:
            return GLFW_KEY_A;
        case KeyInput::KEY_B:
            return GLFW_KEY_B;
        case KeyInput::KEY_C:
            return GLFW_KEY_C;
        case KeyInput::KEY_D:
            return GLFW_KEY_D;
        case KeyInput::KEY_E:
            return GLFW_KEY_E;
        case KeyInput::KEY_F:
            return GLFW_KEY_F;
        case KeyInput::KEY_G:
            return GLFW_KEY_G;
        case KeyInput::KEY_H:
            return GLFW_KEY_H;
        case KeyInput::KEY_I:
            return GLFW_KEY_I;
        case KeyInput::KEY_J:
            return GLFW_KEY_J;
        case KeyInput::KEY_K:
            return GLFW_KEY_K;
        case KeyInput::KEY_L:
            return GLFW_KEY_L;
        case KeyInput::KEY_M:
            return GLFW_KEY_M;
        case KeyInput::KEY_N:
            return GLFW_KEY_N;
        case KeyInput::KEY_O:
            return GLFW_KEY_O;
        case KeyInput::KEY_P:
            return GLFW_KEY_P;
        case KeyInput::KEY_Q:
            return GLFW_KEY_Q;
        case KeyInput::KEY_R:
            return GLFW_KEY_R;
        case KeyInput::KEY_S:
            return GLFW_KEY_S;
        case KeyInput::KEY_T:
            return GLFW_KEY_T;
        case KeyInput::KEY_U:
            return GLFW_KEY_U;
        case KeyInput::KEY_V:
            return GLFW_KEY_V;
        case KeyInput::KEY_W:
            return GLFW_KEY_W;
        case KeyInput::KEY_X:
            return GLFW_KEY_X;
        case KeyInput::KEY_Y:
            return GLFW_KEY_Y;
        case KeyInput::KEY_Z:
            return GLFW_KEY_Z;
        case KeyInput::KEY_LEFT_BRACKET:
            return GLFW_KEY_LEFT_BRACKET;
        case KeyInput::KEY_BACKSLASH:
            return GLFW_KEY_BACKSLASH;
        case KeyInput::KEY_RIGHT_BRACKET:
            return GLFW_KEY_RIGHT_BRACKET;
        case KeyInput::KEY_GRAVE_ACCENT:
            return GLFW_KEY_GRAVE_ACCENT;
        case KeyInput::KEY_WORLD_1:
            return GLFW_KEY_WORLD_1;
        case KeyInput::KEY_WORLD_2:
            return GLFW_KEY_WORLD_2;
        case KeyInput::KEY_ESCAPE:
            return GLFW_KEY_ESCAPE;
        case KeyInput::KEY_ENTER:
            return GLFW_KEY_ENTER;
        case KeyInput::KEY_TAB:
            return GLFW_KEY_TAB;
        case KeyInput::KEY_BACKSPACE:
            return GLFW_KEY_BACKSPACE;
        case KeyInput::KEY_INSERT:
            return GLFW_KEY_INSERT;
        case KeyInput::KEY_DELETE:
            return GLFW_KEY_DELETE;
        case KeyInput::KEY_RIGHT:
            return GLFW_KEY_RIGHT;
        case KeyInput::KEY_LEFT:
            return GLFW_KEY_LEFT;
        case KeyInput::KEY_DOWN:
            return GLFW_KEY_DOWN;
        case KeyInput::KEY_UP:
            return GLFW_KEY_UP;
        case KeyInput::KEY_PAGE_UP:
            return GLFW_KEY_PAGE_UP;
        case KeyInput::KEY_PAGE_DOWN:
            return GLFW_KEY_PAGE_DOWN;
        case KeyInput::KEY_HOME:
            return GLFW_KEY_HOME;
        case KeyInput::KEY_END:
            return GLFW_KEY_END;
        case KeyInput::KEY_CAPS_LOCK:
            return GLFW_KEY_CAPS_LOCK;
        case KeyInput::KEY_SCROLL_LOCK:
            return GLFW_KEY_SCROLL_LOCK;
        case KeyInput::KEY_NUM_LOCK:
            return GLFW_KEY_NUM_LOCK;
        case KeyInput::KEY_PRINT_SCREEN:
            return GLFW_KEY_PRINT_SCREEN;
        case KeyInput::KEY_PAUSE:
            return GLFW_KEY_PAUSE;
        case KeyInput::KEY_F1:
            return GLFW_KEY_F1;
        case KeyInput::KEY_F2:
            return GLFW_KEY_F2;
        case KeyInput::KEY_F3:
            return GLFW_KEY_F3;
        case KeyInput::KEY_F4:
            return GLFW_KEY_F4;
        case KeyInput::KEY_F5:
            return GLFW_KEY_F5;
        case KeyInput::KEY_F6:
            return GLFW_KEY_F6;
        case KeyInput::KEY_F7:
            return GLFW_KEY_F7;
        case KeyInput::KEY_F8:
            return GLFW_KEY_F8;
        case KeyInput::KEY_F9:
            return GLFW_KEY_F9;
        case KeyInput::KEY_F10:
            return GLFW_KEY_F10;
        case KeyInput::KEY_F11:
            return GLFW_KEY_F11;
        case KeyInput::KEY_F12:
            return GLFW_KEY_F12;
        case KeyInput::KEY_F13:
            return GLFW_KEY_F13;
        case KeyInput::KEY_F14:
            return GLFW_KEY_F14;
        case KeyInput::KEY_F15:
            return GLFW_KEY_F15;
        case KeyInput::KEY_F16:
            return GLFW_KEY_F16;
        case KeyInput::KEY_F17:
            return GLFW_KEY_F17;
        case KeyInput::KEY_F18:
            return GLFW_KEY_F18;
        case KeyInput::KEY_F19:
            return GLFW_KEY_F19;
        case KeyInput::KEY_F20:
            return GLFW_KEY_F20;
        case KeyInput::KEY_F21:
            return GLFW_KEY_F21;
        case KeyInput::KEY_F22:
            return GLFW_KEY_F22;
        case KeyInput::KEY_F23:
            return GLFW_KEY_F23;
        case KeyInput::KEY_F24:
            return GLFW_KEY_F24;
        case KeyInput::KEY_F25:
            return GLFW_KEY_F25;
        case KeyInput::KEY_KP_0:
            return GLFW_KEY_KP_0;
        case KeyInput::KEY_KP_1:
            return GLFW_KEY_KP_1;
        case KeyInput::KEY_KP_2:
            return GLFW_KEY_KP_2;
        case KeyInput::KEY_KP_3:
            return GLFW_KEY_KP_3;
        case KeyInput::KEY_KP_4:
            return GLFW_KEY_KP_4;
        case KeyInput::KEY_KP_5:
            return GLFW_KEY_KP_5;
        case KeyInput::KEY_KP_6:
            return GLFW_KEY_KP_6;
        case KeyInput::KEY_KP_7:
            return GLFW_KEY_KP_7;
        case KeyInput::KEY_KP_8:
            return GLFW_KEY_KP_8;
        case KeyInput::KEY_KP_9:
            return GLFW_KEY_KP_9;
        case KeyInput::KEY_KP_DECIMAL:
            return GLFW_KEY_KP_DECIMAL;
        case KeyInput::KEY_KP_DIVIDE:
            return GLFW_KEY_KP_DIVIDE;
        case KeyInput::KEY_KP_MULTIPLY:
            return GLFW_KEY_KP_MULTIPLY;
        case KeyInput::KEY_KP_SUBTRACT:
            return GLFW_KEY_KP_SUBTRACT;
        case KeyInput::KEY_KP_ADD:
            return GLFW_KEY_KP_ADD;
        case KeyInput::KEY_KP_ENTER:
            return GLFW_KEY_KP_ENTER;
        case KeyInput::KEY_KP_EQUAL:
            return GLFW_KEY_KP_EQUAL;
        case KeyInput::KEY_LEFT_SHIFT:
            return GLFW_KEY_LEFT_SHIFT;
        case KeyInput::KEY_LEFT_CONTROL:
            return GLFW_KEY_LEFT_CONTROL;
        case KeyInput::KEY_LEFT_ALT:
            return GLFW_KEY_LEFT_ALT;
        case KeyInput::KEY_LEFT_SUPER:
            return GLFW_KEY_LEFT_SUPER;
        case KeyInput::KEY_RIGHT_SHIFT:
            return GLFW_KEY_RIGHT_SHIFT;
        case KeyInput::KEY_RIGHT_CONTROL:
            return GLFW_KEY_RIGHT_CONTROL;
        case KeyInput::KEY_RIGHT_ALT:
            return GLFW_KEY_RIGHT_ALT;
        case KeyInput::KEY_RIGHT_SUPER:
            return GLFW_KEY_RIGHT_SUPER;
        case KeyInput::KEY_MENU:
            return GLFW_KEY_MENU;
        default:
            return GLFW_INVALID_VALUE;
    }
}
