name: Build Matrix

on:
  pull_request:
  push:

jobs:
  skip-duplicates:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          cancel_others: 'true'
          # Will ignore data because our checks don't use it yet
          paths_ignore: '["README.md", "docs/**", "tools/**", "data/**"]'

  build:
    needs: skip-duplicates
    # Skip tasks
    if: ${{ needs.skip-duplicates.outputs.should_skip != 'true' }}
    strategy:
      matrix:
        config: [Release, Debug]
        compiler: [gcc, clang]
        os: [windows-latest, ubuntu-latest]

    name: ${{ matrix.title }} ${{ matrix.config }}
    runs-on: ${{ matrix.os }}
    steps:
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - if: ${{ matrix.os != 'windows-latest' }}
      name: Set compiler
      run: |
        echo "CC=${{ matrix.compiler == 'gcc' && 'gcc' || 'clang'   }}" >> $GITHUB_ENV
        echo "CXX=${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }}" >> $GITHUB_ENV
        echo "CMAKE_C_COMPILER_LAUNCHER=ccache" >> $GITHUB_ENV
        echo "CMAKE_CXX_COMPILER_LAUNCHER=ccache" >> $GITHUB_ENV

    - if: ${{ matrix.os != 'windows-latest' }}
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: build${{ matrix.os }}-${{ matrix.compiler }}-${{ matrix.config }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install -y libglfw3 libglfw3-dev libopenal-dev

    - name: Configure Build files
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }}

    - name: Build Conquer Space
      run: |
        cmake --build build --parallel --config ${{ matrix.config }}

    - name: Tests
      run: |
        ctest -V --schedule-random --progress --output-on-failure --parallel --no-tests error --build-config ${{ matrix.config }} --test-dir build/test

    - uses: actions/upload-artifact@v2
      with:
        name: Conquer-Space_${{ matrix.os }}_${{ matrix.config }}_b${{ github.run_number }}
        path: |
          binaries
