name: C++ Linting

on:
  push:
  pull_request:

jobs:
  cpp-lint:
    name: C++ Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: |
        sudo pip install cpplint

    - name: Linting
      run: |
        cpplint --quiet --linelength=120 --recursive --filter=-readability/casting,-runtime/references,-whitespace/newline,-build/c++11,-readability/check,-whitespace/comments,-runtime/int,-build/include_order,-build/include_subdir --verbose=0 src test
