name: deploy-documentation

on:
  pull_request:
  push:
    #branches:
    #- master

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Create Doxygen
      uses: mattnotmitt/doxygen-action@v1.9.2
      with:
        working-directory: './docs'
        doxyfile-path: 'Doxyfile'
    - name: Echo token
      env:
        WHO_TO_TRUST: ${{ secrets.API_TOKEN_GITHUB }}
        TEST2: ${{ secrets.NON_EXST }}
      run: |
        if [ -z "$WHO_TO_TRUST" ]
        then
          echo "idk if this will worksh"
        fi
        if [ -z "$TEST2" ]
        then
          echo "idkkkk if this will works2t"
        fi

    - name: Pushes to another repository
      uses: EhWhoAmI/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'docs/html'
        destination-github-username: EhWhoAmI
        destination-repository-username: Conquer-Space
        destination-repository-name: Conquer-Space.github.io
        user-email: carles3@pina.cat
        target-branch: main
        user-name: EhWhoAmI
        target-directory: docs
