name: deploy-documentation

on:
  pull_request:
  push:
    #branches:
    #- master

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: Doxygen create
      uses: mattnotmitt/doxygen-action@v1.9.2
      with:
        doxyfile-path: 'doxygen_docs/Doxygen'

    # Push the book's HTML to github-pages
    - name: Push to Github Pages
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'doxygen_docs/html'
        destination-github-username: 'Conquer-Space'
        destination-repository-name: 'Conquer-Space.github.io'
        user-email: github-actions[bot]@users.noreply.github.com
        target-branch: main
        target-directory: docs
