name: deploy-documentation

on:
  pull_request:
  push:
    #branches:
    #- master

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Create Doxygen
      uses: mattnotmitt/doxygen-action@v1.9.2
      with:
        working-directory: './doxygen_docs'
        doxyfile-path: 'Doxyfile'

    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'doxygen_docs/html'
        destination-github-username: 'Conquer-Space'
        destination-repository-name: 'Conquer-Space.github.io'
        user-email: carles3@pina.cat
        target-branch: main
        target-directory: docs
