name: Linux

on: [ pull_request, push ]

jobs:
  build:
    strategy:
      matrix:
        config: [Release, Debug]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install -y libglfw3 libglfw3-dev libopenal-dev

    - name: Configure Build files
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }}

    - name: Build Conquer Space
      run: |
        cmake --build build --parallel --config ${{ matrix.config }}

    - name: Tests
      run: |
        ctest --schedule-random --progress --output-on-failure --parallel --no-tests error --build-config ${{ matrix.config }} --test-dir build/test

    - uses: actions/upload-artifact@v2
      with:
        name: Conquer-Space_${{ matrix.config }}_b${{ github.run_number }}
        path: |
          binaries
