name: Windows

on: [ pull_request, push ]

jobs:
  build:
    strategy:
      matrix:
        config: [Release, Debug]
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive
    - name: Generate Build Files
      run: |
        cmake -B build -DTESTS=ON -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_TOOLCHAIN_FILE=x64-windows -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake

    - name: Build Conquer Space
      run: |
        cmake --build build --parallel --config ${{ matrix.config }}

    - name: Run Tests
      run: ctest -V --schedule-random --progress --output-on-failure --parallel --no-tests error --build-config ${{ matrix.config }} --test-dir build/test

    - uses: actions/upload-artifact@v2
      with:
        name: Conquer-Space_win32_${{ matrix.config }}_${{ github.run_number }}
        path: |
          binaries
